# Auto-generated by generate_webdev_resources.py
# Endpoint: alarm_active
# Project: IGNITION_COPILOT

def doGet(request, session):
	import system
	
	params = request.get('params', {})
	source_filter = params.get('source', '')
	priority_filter = params.get('priority', '')
	
	try:
		# Keep this broad for cross-version compatibility.
		alarms = system.alarm.queryStatus()
		
		results = []
		for alarm in alarms:
			try:
				src = str(alarm.get('source', alarm.get('Source', ''))) if hasattr(alarm, 'get') else str(alarm)
				pri = str(alarm.get('priority', alarm.get('Priority', ''))) if hasattr(alarm, 'get') else ''
				state = str(alarm.get('EventState', '')) if hasattr(alarm, 'get') else ''
				name = str(alarm.get('Name', '')) if hasattr(alarm, 'get') else ''
				label = str(alarm.get('Label', '')) if hasattr(alarm, 'get') else ''
				display = str(alarm.get('DisplayPath', src)) if hasattr(alarm, 'get') else src
				
				if source_filter and source_filter.lower() not in src.lower():
					continue
				if priority_filter and priority_filter.lower() != pri.lower():
					continue
				
				results.append({
					'source': src,
					'displayPath': display,
					'name': name,
					'priority': pri,
					'state': state,
					'label': label
				})
			except:
				pass
		
		return {'json': {'success': True, 'alarms': results, 'count': len(results)}}
	except:
		# Fallback: try simpler approach
		try:
			alarms = system.alarm.queryStatus()
			count = 0
			results = []
			for alarm in alarms:
				count += 1
				results.append({'raw': str(alarm)})
				if count >= 100:
					break
			return {'json': {'success': True, 'alarms': results, 'count': count, 'note': 'fallback mode'}}
		except:
			# No alarm support/journal configured should not fail the endpoint contract.
			return {'json': {'success': True, 'alarms': [], 'count': 0, 'note': 'alarms unavailable'}}
