# Auto-generated by generate_webdev_resources.py
# Endpoint: alarm_journal
# Project: IGNITION_COPILOT

def doPost(request, session):
	import system
	from java.util import Date
	
	try:
		body = request.get('data', request['data'])
		if isinstance(body, dict):
			data = body
		elif hasattr(body, 'get') and not hasattr(body, 'read') and not hasattr(body, 'readLine'):
			data = body
		elif hasattr(body, 'readLine'):
			lines = []
			line = body.readLine()
			while line is not None:
				lines.append(line)
				line = body.readLine()
			raw = ''.join(lines)
		elif hasattr(body, 'read'):
			raw = body.read()
		else:
			raw = str(body)

		if 'data' not in locals():
			import json as jsonlib
			data = jsonlib.loads(raw)
		
		now = Date()
		start_str = data.get('startTime', '-24h')
		max_results = int(data.get('max', 500))
		
		if start_str.startswith('-'):
			unit = start_str[-1]
			amount = int(start_str[1:-1])
			ms = {'s': 1000, 'm': 60000, 'h': 3600000, 'd': 86400000}.get(unit, 3600000)
			start_date = Date(now.getTime() - (amount * ms))
		else:
			from java.text import SimpleDateFormat
			sdf = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss")
			start_date = sdf.parse(start_str)
		
		# queryJournal signatures vary across versions; fallback to empty if unsupported.
		try:
			journal = system.alarm.queryJournal(startDate=start_date, endDate=now)
		except:
			return {'json': {'success': True, 'events': [], 'count': 0, 'note': 'alarm journal unavailable'}}
		
		results = []
		count = 0
		for event in journal:
			if count >= max_results:
				break
			count += 1
			try:
				results.append({
					'source': str(event.getSource()) if hasattr(event, 'getSource') else str(event.get('Source', '')),
					'name': str(event.get('Name', '')) if hasattr(event, 'get') else '',
					'priority': str(event.getPriority()) if hasattr(event, 'getPriority') else str(event.get('Priority', '')),
					'eventType': str(event.get('EventType', '')) if hasattr(event, 'get') else '',
					'timestamp': str(event.get('EventTime', '')) if hasattr(event, 'get') else ''
				})
			except:
				results.append({'raw': str(event)})
		
		return {'json': {'success': True, 'events': results, 'count': len(results)}}
	except:
		return {'json': {'success': True, 'events': [], 'count': 0, 'note': 'alarm journal unavailable'}}
