# Auto-generated by generate_webdev_resources.py
# Endpoint: history_query
# Project: IGNITION_COPILOT

def doPost(request, session):
	import system
	from java.util import Date
	from java.text import SimpleDateFormat
	
	try:
		body = request.get('data', request['data'])
		if isinstance(body, dict):
			data = body
		elif hasattr(body, 'get') and not hasattr(body, 'read') and not hasattr(body, 'readLine'):
			data = body
		elif hasattr(body, 'readLine'):
			lines = []
			line = body.readLine()
			while line is not None:
				lines.append(line)
				line = body.readLine()
			raw = ''.join(lines)
		elif hasattr(body, 'read'):
			raw = body.read()
		else:
			raw = str(body)

		if 'data' not in locals():
			import json as jsonlib
			data = jsonlib.loads(raw)
		
		paths = data.get('paths', [])
		if not paths:
			return {'json': {'success': False, 'error': 'No paths provided'}}
		
		return_size = int(data.get('returnSize', 500))
		sdf = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss")
		now = Date()
		
		start_str = data.get('startTime', '')
		end_str = data.get('endTime', '')
		
		if start_str.startswith('-'):
			unit = start_str[-1]
			amount = int(start_str[1:-1])
			ms = {'s': 1000, 'm': 60000, 'h': 3600000, 'd': 86400000}.get(unit, 3600000)
			start_date = Date(now.getTime() - (amount * ms))
		elif start_str:
			start_date = sdf.parse(start_str)
		else:
			start_date = Date(now.getTime() - 3600000)
		
		if end_str and end_str.startswith('-'):
			unit = end_str[-1]
			amount = int(end_str[1:-1])
			ms = {'s': 1000, 'm': 60000, 'h': 3600000, 'd': 86400000}.get(unit, 3600000)
			end_date = Date(now.getTime() - (amount * ms))
		elif end_str:
			end_date = sdf.parse(end_str)
		else:
			end_date = now
		
		all_results = {}
		for path in paths:
			try:
				ds = system.tag.queryTagHistory(
					paths=[path],
					startDate=start_date,
					endDate=end_date,
					returnSize=return_size,
					returnFormat='Wide'
				)
				
				records = []
				for row in range(ds.getRowCount()):
					ts = ds.getValueAt(row, 0)
					val = ds.getValueAt(row, 1) if ds.getColumnCount() > 1 else None
					records.append({'timestamp': str(ts), 'value': val})
				
				all_results[path] = {'records': records, 'count': len(records)}
			except Exception as e:
				all_results[path] = {'error': str(e), 'records': [], 'count': 0}
		
		return {'json': {'success': True, 'data': all_results}}
	except Exception as e:
		return {'json': {'success': False, 'error': str(e)}}
