# Auto-generated by generate_webdev_resources.py
# Endpoint: script_exec
# Project: IGNITION_COPILOT

def doPost(request, session):
	import system
	
	try:
		body = request.get('data', request['data'])
		if isinstance(body, dict):
			data = body
		elif hasattr(body, 'get') and not hasattr(body, 'read') and not hasattr(body, 'readLine'):
			data = body
		elif hasattr(body, 'readLine'):
			lines = []
			line = body.readLine()
			while line is not None:
				lines.append(line)
				line = body.readLine()
			raw = ''.join(lines)
		elif hasattr(body, 'read'):
			raw = body.read()
		else:
			raw = str(body)

		if 'data' not in locals():
			import json as jsonlib
			data = jsonlib.loads(raw)
		
		expression = data.get('expression', '')
		if not expression:
			return {'json': {'success': False, 'error': 'No expression provided'}}
		
		result = system.tag.readBlocking([expression])
		if result and len(result) > 0:
			val = result[0].value
			if hasattr(val, 'toString'):
				val = str(val)
			return {'json': {'success': True, 'result': val, 'quality': str(result[0].quality)}}
		
		return {'json': {'success': False, 'error': 'Expression returned no result'}}
	except Exception as e:
		return {'json': {'success': False, 'error': str(e)}}
