# Auto-generated by generate_webdev_resources.py
# Endpoint: system_info
# Project: IGNITION_COPILOT

def doGet(request, session):
	import system

	try:
		provider_names = []
		try:
			providers = system.tag.getProviders()
			for provider in providers:
				provider_names.append(str(provider))
		except:
			provider_names = ['default']

		gateway_name = ''
		try:
			gateway_name = str(system.tag.readBlocking(['[System]Gateway/SystemName'])[0].value)
		except:
			gateway_name = 'Unknown'

		info = {
			'gatewayName': gateway_name,
			'systemName': gateway_name,
			'timestamp': str(system.date.now()),
			'tagProviders': provider_names,
		}

		return {'json': {'success': True, 'info': info}}
	except Exception as e:
		return {'json': {'success': False, 'error': str(e)}}
