# Auto-generated by generate_webdev_resources.py
# Endpoint: tag_config
# Project: IGNITION_COPILOT

def doGet(request, session):
	import system
	
	params = request.get('params', {})
	path = params.get('path', '')
	
	if not path:
		return {'json': {'success': False, 'error': 'Missing path parameter'}}
	
	try:
		# Try reading tag to confirm it exists and get basic info
		qv = system.tag.readBlocking([path])[0]
		
		# Browse to get type info
		parent = path.rsplit('/', 1)[0] if '/' in path else path.rsplit(']', 1)[0] + ']'
		tag_name = path.rsplit('/', 1)[-1] if '/' in path else path
		
		browse_results = system.tag.browse(parent)
		tag_info = None
		for t in browse_results:
			if t['name'] == tag_name:
				tag_info = t
				break
		
		config = {
			'path': path,
			'value': qv.value if hasattr(qv.value, '__class__') and qv.value.__class__.__name__ not in ['JavaObject'] else str(qv.value),
			'quality': str(qv.quality),
			'timestamp': str(qv.timestamp),
		}
		
		if tag_info:
			config['tagType'] = str(tag_info.get('tagType', ''))
			config['hasChildren'] = tag_info.get('hasChildren', False)
			if 'dataType' in tag_info:
				config['dataType'] = str(tag_info['dataType'])
			if 'valueSource' in tag_info:
				config['valueSource'] = str(tag_info['valueSource'])
		
		return {'json': {'success': True, 'path': path, 'config': config}}
	except Exception as e:
		return {'json': {'success': False, 'error': str(e), 'path': path}}


def doPost(request, session):
	import system
	
	try:
		body = request.get('data', request['data'])
		if isinstance(body, dict):
			data = body
		elif hasattr(body, 'get') and not hasattr(body, 'read') and not hasattr(body, 'readLine'):
			data = body
		elif hasattr(body, 'readLine'):
			lines = []
			line = body.readLine()
			while line is not None:
				lines.append(line)
				line = body.readLine()
			raw = ''.join(lines)
		elif hasattr(body, 'read'):
			raw = body.read()
		else:
			raw = str(body)

		if 'data' not in locals():
			import json as jsonlib
			data = jsonlib.loads(raw)
		
		base_path = data.pop('basePath', '')
		if not base_path:
			full_path = data.get('path', data.get('name', ''))
			if '/' in full_path:
				parts = full_path.rsplit('/', 1)
				base_path = parts[0]
				data['name'] = parts[1]
			else:
				return {'json': {'success': False, 'error': 'basePath or full path required'}}
		
		data.setdefault('tagType', 'AtomicTag')
		data.setdefault('dataType', 'Float8')
		
		result = system.tag.configure(base_path, [data], 'o')
		statuses = [str(r) for r in result]
		
		return {'json': {'success': True, 'basePath': base_path, 'results': statuses}}
	except Exception as e:
		return {'json': {'success': False, 'error': str(e)}}
