# Auto-generated by generate_webdev_resources.py
# Endpoint: tag_read
# Project: IGNITION_COPILOT

def doGet(request, session):
	import system

	params = request.get('params', {})
	raw_paths = params.get('paths', '')

	if isinstance(raw_paths, list):
		paths = [str(p).strip() for p in raw_paths if str(p).strip()]
	else:
		paths = [p.strip() for p in str(raw_paths).split(',') if p.strip()]

	if not paths:
		return {'json': {'success': False, 'error': 'No paths provided', 'results': []}}

	try:
		values = system.tag.readBlocking(paths)
		results = []
		for idx, qv in enumerate(values):
			val = qv.value
			if hasattr(val, 'toString'):
				try:
					val = str(val)
				except:
					pass

			results.append({
				'path': paths[idx],
				'value': val,
				'quality': str(qv.quality),
				'timestamp': str(qv.timestamp),
				'success': qv.quality.isGood() if hasattr(qv.quality, 'isGood') else True,
			})

		return {'json': {'success': True, 'results': results, 'count': len(results)}}
	except Exception as e:
		return {'json': {'success': False, 'error': str(e), 'results': []}}
