# Auto-generated by generate_webdev_resources.py
# Endpoint: tag_search
# Project: IGNITION_COPILOT

def doGet(request, session):
	import system
	
	params = request.get('params', {})
	root = params.get('root', '[default]')
	pattern = params.get('pattern', '*').lower()
	tag_type = params.get('tagType', '')
	max_results = int(params.get('max', '200'))
	
	try:
		tags = system.tag.browse(root, {'recursive': True})
		
		matches = []
		for tag in tags:
			if len(matches) >= max_results:
				break
			name = tag['name']
			tt = str(tag['tagType'])
			
			if tag_type and tt != tag_type:
				continue
			
			# Simple glob matching: * = anything, ? = single char
			if pattern == '*':
				matched = True
			elif pattern.startswith('*') and pattern.endswith('*'):
				# *xyz* = contains
				matched = pattern[1:-1] in name.lower()
			elif pattern.startswith('*'):
				# *xyz = endswith
				matched = name.lower().endswith(pattern[1:])
			elif pattern.endswith('*'):
				# xyz* = startswith
				matched = name.lower().startswith(pattern[:-1])
			else:
				matched = name.lower() == pattern
			
			if matched:
				matches.append({
					'name': name,
					'path': str(tag['fullPath']),
					'tagType': tt,
					'hasChildren': tag['hasChildren']
				})
		
		return {'json': {'success': True, 'matches': matches, 'count': len(matches), 'pattern': pattern}}
	except Exception as e:
		return {'json': {'success': False, 'error': str(e)}}
