# Auto-generated by generate_webdev_resources.py
# Endpoint: tag_browse
# Project: IGNITION_COPILOT

def doGet(request, session):
	import system

	params = request.get('params', {})
	path = params.get('path', '[default]')
	recursive = str(params.get('recursive', 'false')).lower() == 'true'

	try:
		results = system.tag.browse(path, {'recursive': recursive})
		tags = []
		for tag in results:
			tags.append({
				'name': str(tag.get('name', '')),
				'path': str(tag.get('fullPath', '')),
				'tagType': str(tag.get('tagType', '')),
				'dataType': str(tag.get('dataType', '')) if tag.get('dataType') is not None else '',
				'valueSource': str(tag.get('valueSource', '')) if tag.get('valueSource') is not None else '',
				'hasChildren': bool(tag.get('hasChildren', False)),
			})

		return {
			'json': {
				'success': True,
				'path': path,
				'recursive': recursive,
				'count': len(tags),
				'tags': tags,
			}
		}
	except Exception as e:
		return {'json': {'success': False, 'error': str(e), 'path': path}}
