# Auto-generated by generate_webdev_resources.py
# Endpoint: tag_delete
# Project: IGNITION_COPILOT

def doPost(request, session):
	import system
	
	try:
		body = request.get('data', request['data'])
		if isinstance(body, dict):
			data = body
		elif hasattr(body, 'get') and not hasattr(body, 'read') and not hasattr(body, 'readLine'):
			data = body
		elif hasattr(body, 'readLine'):
			lines = []
			line = body.readLine()
			while line is not None:
				lines.append(line)
				line = body.readLine()
			raw = ''.join(lines)
		elif hasattr(body, 'read'):
			raw = body.read()
		else:
			raw = str(body)

		if 'data' not in locals():
			import json as jsonlib
			data = jsonlib.loads(raw)
		
		paths = data.get('paths', [])
		if isinstance(paths, str):
			paths = [paths]
		
		if not paths:
			return {'json': {'success': False, 'error': 'No paths provided'}}
		
		results = []
		for path in paths:
			try:
				system.tag.deleteTags([path])
				results.append({'path': path, 'success': True})
			except Exception as e:
				results.append({'path': path, 'success': False, 'error': str(e)})
		
		all_ok = all(r.get('success', False) for r in results)
		return {'json': {'success': all_ok, 'results': results}}
	except Exception as e:
		return {'json': {'success': False, 'error': str(e)}}
