# Auto-generated by generate_webdev_resources.py
# Endpoint: tag_write
# Project: IGNITION_COPILOT

def doPost(request, session):
	import system
	
	try:
		body = request.get('data', request['data'])
		if isinstance(body, dict):
			data = body
		elif hasattr(body, 'get') and not hasattr(body, 'read') and not hasattr(body, 'readLine'):
			data = body
		elif hasattr(body, 'readLine'):
			lines = []
			line = body.readLine()
			while line is not None:
				lines.append(line)
				line = body.readLine()
			raw = ''.join(lines)
		elif hasattr(body, 'read'):
			raw = body.read()
		else:
			raw = str(body)

		if 'data' not in locals():
			import json as jsonlib
			data = jsonlib.loads(raw)
		
		writes = data.get('writes', [])
		if not writes and 'path' in data:
			writes = [{'path': data['path'], 'value': data['value']}]
		
		if not writes:
			return {'json': {'success': False, 'error': 'No writes provided'}}
		
		results = []
		for w in writes:
			path = w.get('path', '')
			value = w.get('value')
			if not path:
				results.append({'path': '', 'success': False, 'error': 'Empty path'})
				continue
			try:
				qv = system.tag.writeBlocking([path], [value])
				results.append({
					'path': path,
					'success': qv[0].isGood(),
					'quality': str(qv[0])
				})
			except Exception as e:
				results.append({'path': path, 'success': False, 'error': str(e)})
		
		all_ok = all(r.get('success', False) for r in results)
		return {'json': {'success': all_ok, 'results': results}}
	except Exception as e:
		return {'json': {'success': False, 'error': str(e)}}
