#!/usr/bin/env python3
"""Generate one-file-per-endpoint Ignition WebDev script resources.

This does not modify an Ignition project directly. It prepares files that can be
copied into Designer WebDev resources quickly and consistently.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

from fixed_webdev_scripts import get_webdev_scripts


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate endpoint scripts for Ignition WebDev resources."
    )
    parser.add_argument(
        "--output-dir",
        default="mcp-server/ignition-automation/webdev-resources",
        help="Directory to write generated endpoint scripts.",
    )
    parser.add_argument(
        "--project",
        default="ignition-copilot",
        help="Ignition project name these resources belong to.",
    )
    return parser.parse_args()


def write_files(output_dir: Path, project: str) -> None:
    scripts = get_webdev_scripts()
    output_dir.mkdir(parents=True, exist_ok=True)

    manifest = {
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "project": project,
        "resourcePath": f"/system/webdev/{project}/<resource>",
        "resourceNames": list(scripts.keys()),
        "notes": [
            "Create one WebDev resource per name under system/webdev/<project>/.",
            "Paste each corresponding script file into the resource's script editor.",
            "Save and publish the project, then run mcp-server/test_endpoints.py.",
        ],
    }

    for name, script_body in scripts.items():
        target = output_dir / f"{name}.py"
        header = (
            f"# Auto-generated by generate_webdev_resources.py\n"
            f"# Endpoint: {name}\n"
            f"# Project: {project}\n\n"
        )
        target.write_text(header + script_body.strip() + "\n", encoding="utf-8")

    (output_dir / "manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n",
        encoding="utf-8",
    )

    print(f"Generated {len(scripts)} endpoint scripts in: {output_dir}")
    print("Next step: paste each file into a matching Ignition WebDev resource.")


def main() -> None:
    args = parse_args()
    write_files(Path(args.output_dir), args.project)


if __name__ == "__main__":
    main()
